import localFont from 'next/font/local';
import './_css/globals.css';
import './_css/prism.css';
import './_css/extra.css';
import { ThemeProvider } from 'next-themes';
import { SiteData } from '@/data/SiteData';
import ScrollProgressBar from './_components/ScrollProgressBar';
import ScrollTop from './_components/ScrollTop';
import { LayoutWrapper } from './_components/LayoutWrapper';
import { Analytics } from '@vercel/analytics/react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

/**
 * Root layout component that wraps the application with theme, analytics, and layout providers.
 * @param {Readonly<{ children: React.ReactNode }>} props - The children to render inside the layout.
 * @returns {JSX.Element} The rendered root layout.
 */
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black  dark:bg-background-color dark:text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={SiteData.theme}
        >
          <Analytics />
          <ScrollProgressBar />
          <ScrollTop />
          <LayoutWrapper>{children}</LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
